# Generated by Django 6.0.1 on 2026-01-21 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=150, unique=True)),
                ('department', models.CharField(choices=[('EC', 'Electronics and Computer Engineering'), ('MA', 'Mechanical and Automobile Engineering'), ('CA', 'Civil and Architecture Engineering'), ('IN', 'Industrial Engineering')], max_length=2)),
                ('current_semester', models.CharField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1, max_length=1)),
                ('batch_year', models.DateTimeField()),
                ('section', models.CharField(blank=True, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='accounts_st_id_1a3ac3_idx')],
            },
        ),
    ]
