# Generated by Django 6.0.1 on 2026-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.PositiveIntegerField(),
        ),
    ]
