# Generated by Django 6.0.1 on 2026-01-21 12:50

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(help_text='Enter in the format of THA079BEI042 or tha079bei042', max_length=150, unique=True, validators=[accounts.validators.validate_roll_number]),
        ),
    ]
