# Generated by Django 6.0.1 on 2026-01-27 11:38

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, help_text='e.g THA079BEI042', max_length=150, null=True, unique=True, validators=[accounts.validators.validate_roll_number]),
        ),
    ]
