# Generated by Django 6.0.1 on 2026-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
