# Generated by Django 6.0.1 on 2026-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1, max_length=2),
        ),
    ]
