# Generated by Django 6.0.1 on 2026-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=10),
        ),
    ]
