# Generated by Django 6.0.1 on 2026-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
