# Generated by Django 6.0.1 on 2026-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacherprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
