# Generated by Django 6.0.1 on 2026-03-24 11:50

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otptoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('EC', 'Electronics and Computer Engineering'), ('MA', 'Mechanical and Automobile Engineering'), ('CA', 'Civil and Architecture Engineering'), ('IN', 'Industrial Engineering')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, db_index=True, help_text='e.g THA079BEI042', max_length=150, null=True, unique=True, validators=[accounts.validators.validate_roll_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Are you a student?'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user_id'], name='accounts_st_user_id_3ee8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['department', 'current_semester'], name='accounts_st_departm_aae090_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['user_id'], name='accounts_te_user_id_ed7190_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['department'], name='accounts_te_departm_c8a51c_idx'),
        ),
    ]
