# Generated by Django 6.0.1 on 2026-01-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_current_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], default='A', max_length=5),
        ),
    ]
