# Generated by Django 6.0.1 on 2026-01-21 13:21

import accounts.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(help_text='e.g THA079BEI042', max_length=150, unique=True, validators=[accounts.validators.validate_roll_number]),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, choices=[('EC', 'Electronics and Computer Engineering'), ('MA', 'Mechanical and Automobile Engineering'), ('CA', 'Civil and Architecture Engineering'), ('IN', 'Industrial Engineering')], max_length=2, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(help_text='e.g. Assistant Professor, HOD', max_length=100)),
                ('is_full_time', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='accounts_te_id_a93dfb_idx')],
            },
        ),
    ]
