# Generated by Django 6.0.1 on 2026-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentprofile_roll_no_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('PROF', 'Professor'), ('ASSOC', 'Associate Professor'), ('ASST', 'Assistant Professor'), ('LECT', 'Lecturer'), ('ADJ', 'Adjunct Faculty'), ('VISIT', 'Visiting Faculty'), ('TA', 'Teaching Assistant'), ('LAB', 'Lab Instructor')], help_text='e.g. Assistant Professor, HOD', max_length=10),
        ),
    ]
