# Generated by Django 6.0.1 on 2026-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacherprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_full_time',
            field=models.BooleanField(default=True, verbose_name='Full time'),
        ),
    ]
