JAZZMIN_SETTINGS = {
    "site_title": "Gradus Admin",
    "site_header": "Gradus",
    "site_brand": "Gradus Evaluation",
    "welcome_sign": "Welcome to Gradus Admin Portal",
    "copyright": "Gradus College System",
    "search_model": ["accounts.User", "classrooms.Classroom"],
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "accounts.User"},
        {"app": "classrooms"},
    ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "accounts.User": "fas fa-user",
        "accounts.StudentProfile": "fas fa-user-graduate",
        "accounts.TeacherProfile": "fas fa-chalkboard-teacher",
        "classrooms.Classroom": "fas fa-school",
        "tasks.Task": "fas fa-tasks",
        "tasks.TaskSubmission": "fas fa-file-upload",
        "tasks.TaskEvaluation": "fas fa-check-double",
        "resources.Resource": "fas fa-copy",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
