# Generated by Django 6.0.1 on 2026-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
