# Generated by Django 6.0.1 on 2026-03-23 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_delete_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomTaskTypeWeightage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("assessment", "Assessment"),
                            ("lab_report", "Lab Report"),
                            ("quiz", "Quiz"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("include_in_final", models.BooleanField(default=False)),
                (
                    "weightage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="task_type_weightages",
                        to="classrooms.classroom",
                    ),
                ),
            ],
            options={
                "ordering": ("task_type",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classroom", "task_type"),
                        name="unique_classroom_task_type_weightage",
                    ),
                    models.CheckConstraint(
                        condition=Q(("weightage__gte", 0), ("weightage__lte", 100)),
                        name="classroom_weightage_between_0_and_100",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~Q(("include_in_final", True)) | Q(("weightage__gt", 0))
                        ),
                        name="classroom_weightage_positive_when_included",
                    ),
                ],
            },
        ),
    ]
