# Generated by Django 6.0.1 on 2026-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_classroomtasktypeweightage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomtasktypeweightage',
            options={'ordering': ('assessment_component', 'task_type')},
        ),
        migrations.RemoveConstraint(
            model_name='classroomtasktypeweightage',
            name='unique_classroom_task_type_weightage',
        ),
        migrations.AddField(
            model_name='classroomtasktypeweightage',
            name='assessment_component',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], db_index=True, default='theory', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='classroomtasktypeweightage',
            constraint=models.UniqueConstraint(fields=('classroom', 'assessment_component', 'task_type'), name='unique_classroom_component_task_type_weightage'),
        ),
    ]
