# Generated by Django 6.0.1 on 2026-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_classroom_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='invite_code',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
