# Generated by Django 6.0.1 on 2026-03-24 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_alter_classroom_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_component', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], db_index=True, default='theory', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='classrooms.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(db_index=True, default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='classrooms.attendancesession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAttendanceWeightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_component', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], db_index=True, max_length=10)),
                ('include_in_final', models.BooleanField(default=False)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_weightages', to='classrooms.classroom')),
            ],
            options={
                'ordering': ('assessment_component',),
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['classroom', 'assessment_component', 'date'], name='classrooms__classro_fd63e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('classroom', 'assessment_component', 'date'), name='unique_classroom_component_attendance_session_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'session'], name='classrooms__student_a73c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'is_present'], name='classrooms__session_3a6866_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_record_per_student_per_session'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendanceweightage',
            constraint=models.UniqueConstraint(fields=('classroom', 'assessment_component'), name='unique_classroom_component_attendance_weightage'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendanceweightage',
            constraint=models.CheckConstraint(condition=models.Q(('weightage__gte', 0), ('weightage__lte', 100)), name='classroom_attendance_weightage_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendanceweightage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('include_in_final', True), _negated=True), ('weightage__gt', 0), _connector='OR'), name='classroom_attendance_weightage_positive_when_included'),
        ),
    ]
