# Generated by Django 6.0.1 on 2026-03-24 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_attendancesession_attendancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_component', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], db_index=True, default='theory', max_length=10)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='classrooms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['classroom', 'assessment_component'], name='classrooms__classro_03c1f8_idx'), models.Index(fields=['classroom', 'student'], name='classrooms__classro_898df4_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'student', 'assessment_component'), name='unique_classroom_student_component_attendance_summary'), models.CheckConstraint(condition=models.Q(('present_days__gte', 0)), name='attendance_summary_present_days_non_negative'), models.CheckConstraint(condition=models.Q(('total_days__gte', 0)), name='attendance_summary_total_days_non_negative'), models.CheckConstraint(condition=models.Q(('present_days__lte', models.F('total_days'))), name='attendance_summary_present_days_lte_total_days')],
            },
        ),
    ]
