# Generated by Django 6.0.1 on 2026-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevaluation',
            name='feedback',
            field=models.CharField(default=''),
        ),
    ]
