# Generated by Django 6.0.1 on 2026-03-23 11:00

import django.core.validators
import tasks.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.utils.submission_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt', 'zip', 'pptx'])]),
        ),
    ]
