# Generated by Django 6.0.1 on 2026-03-23 12:01

import django.core.validators
import django.db.models.deletion
import tasks.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasksubmission_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='task',
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=tasks.utils.submission_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt', 'zip', 'pptx'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_taskrecord',
                'unique_together': {('task', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='TaskEvaluation',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
