# Generated by Django 6.0.1 on 2026-02-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskevaluation_id_alter_tasksubmission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevaluation',
            name='task',
        ),
    ]
