# Generated by Django 6.0.1 on 2026-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasksubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assessment_component',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], db_index=True, default='theory', max_length=10),
        ),
    ]
