# Generated by Django 6.0.1 on 2026-03-24 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_alter_classroom_created_at_and_more'),
        ('tasks', '0004_task_assessment_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('assessment', 'Assessment'), ('lab_report', 'Lab Report'), ('quiz', 'Quiz')], db_index=True, default='assignment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['classroom', 'status'], name='tasks_task_classro_1c897c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['classroom', 'end_date'], name='tasks_task_classro_2402d4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['task', 'student'], name='tasks_taskr_task_id_a89796_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['task', 'marks_obtained'], name='tasks_taskr_task_id_9da2a1_idx'),
        ),
    ]
