# Generated by Django 6.0.1 on 2026-02-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskevaluation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskevaluation',
            name='student',
        ),
        migrations.AlterField(
            model_name='taskevaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tasks.tasksubmission'),
        ),
    ]
